apiVersion: v1
kind: Service
metadata:
  name: {{ include "express-app.fullname" . }}
  labels:
    app: {{ include "express-app.name" . }}

spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "express-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

