name: Build and Deploy to GKE

on: 
  push:
    branches: [ "main" ]

env:
  # Update secrets in repo settings
  APP_NAME: express-app
  IMAGE_TAG: latest
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  ZONE: ${{ secrets.GCP_ZONE }}
  REGION: ${{ secrets.GCP_REGION }}

permissions:
  contents: 'read' # needed for checkout
  id-token: 'write' # required to mint OIDC tokens

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      # Service account key is stored in GitHub Secrets as GCP_SA_KEY and updated in the repo settings
      - name: Authenticate to GCP using workload identity federation
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          # Get this value from terraform output
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }} 
          service_account: "cloudbuild-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      # Install gcloud CLI
      - name: Set up gloud
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}


      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
        
      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPO_NAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}"
          docker build -t $IMAGE -f express-app/Dockerfile express-app
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Get kubeconfig
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Install GKE auth plugin
      # Add Google Cloud's apt key
      # Add Google Cloud SDK repository securely
      # Update and install plugin
        run: |
           echo "Installing gke-gcloud-auth-plugin..."
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg

            
            sudo mkdir -p /usr/share/keyrings
            curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /tmp/google-cloud.gpg > /dev/null
            sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg /tmp/google-cloud.gpg

            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
              | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list

            sudo apt-get update -y
            sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin            

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      # - name: Deploy Helm chart
      #   env:
      #     USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      #   run: |
      #     helm upgrade --install express-app ./helm/express-app \
      #       --namespace default \
      #       --set image.repository=${{ env.IMAGE }} \
      #       --set image.tag=${{ env.IMAGE_TAG }} \
            
  