name: Build and Deploy to Cloud Run

on: 
  push:
    branches: [ "main" ]

env:
  PRPJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  APP_NAME: my-app
  REPO_NAME: ${{ secrets.GCP_REPO_NAME }}  # Match terraform repo_id


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # Service account key is stored in GitHub Secrets as GCP_SA_KEY and updated in the repo settings
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install gcloud CLI
      - name: Set up gloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      
    # Verify gcloud authentication
      - name: Verify gcloud authentication
        run: |
          gcloud auth list

      # Verify Artifact Registry access

      - name: Verify Artifact Registry access
        run: |
          gcloud artifacts repositories list --location=${{ secrets.GCP_REGION }}

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
        
      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPO_NAME }}/${{ env.APP_NAME }}:latest"
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # Push Docker image to Artifact Registry

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.IMAGE }}
    # Deploy to Cloud Run


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-app \
            --image ${{ env.IMAGE }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated 
